#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>

// The entry point generated by the Autarky LLVM Backend
extern uint64_t autarky_main();

int main() {
    // Execute the native machine code
    uint64_t result = autarky_main();
    
    printf("🎉 NATIVE EXECUTION SUCCESSFUL!\n");
    printf("FINAL RESULT: %llu\n", result);
    printf("=====================================\n");
    
    return 0;
}