// runtime.c
#include <stdio.h>
#include <stdint.h>

// Declare the function generated by our Rust compiler
extern int64_t autarky_main();

void print_autarky_result(int64_t* pair_ptr) {
    if (!pair_ptr) {
        printf("Result: NULL\n");
        return;
    }

    // Autarky result is Pair(OldValue, NewArrayPtr)
    int64_t old_val = pair_ptr[0];
    int64_t* array_ptr = (int64_t*)pair_ptr[1];

    printf("\n=====================================\n");
    printf("🎉 NATIVE EXECUTION SUCCESSFUL!\n");
    printf("FINAL RESULT: Pair(Int(%lld), Array([...]))\n", old_val);
    
    if (array_ptr) {
        // Peek at the first element to see the swap result (should be 42)
        printf("Array[0] (Swapped Val): %lld\n", array_ptr[0]);
    }
    printf("=====================================\n");
}

int main() {
    printf("🚀 Booting Autarky Native Runtime...\n");
    
    // Execute the LLVM-generated logic
    int64_t result_addr = autarky_main();
    
    // Interpret the address and print
    print_autarky_result((int64_t*)result_addr);
    
    return 0;
}